import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    appContainer: {
        height: '100%',
        backgroundColor: '#222222',
    },
    topbar: {
        paddingTop: 30,
        height: 110,
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#518BFF',
    },
    searchTopbar: {
        paddingTop: 30,
        height: 174,
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#518BFF',
    },
    topbarTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: 'white',
    },
    searchbar: {
        width: 300,
        borderWidth: 5,
        marginTop: 15,
        borderColor: 'white',
        borderRadius: 20,
        padding: 7,
        backgroundColor: 'white',
        color: 'black',
    },
    list: {
        height: 300,
        alignItems: 'center',
        padding: 15,
        margin: 3,
        backgroundColor: '#28466E',
        borderRadius: 15,
    },
    listTitle: {
        color: '#FFD9AC',
        fontSize: 22,
        paddingHorizontal: 5,
        fontWeight: 'bold',
        marginBottom: 5,
        textAlign: 'center',
        backgroundColor: '#28466E',
        shadowOffset: {width: 1, height: 1},
        shadowOpacity: 1,
        shadowRadius: 1,
    },
    listText: {
        color: '#FFD9AC',
        fontSize: 13,
        paddingHorizontal: 5,
        marginTop: 5,
        textAlign: 'center',
        backgroundColor: '#28466E',
        shadowOffset: {width: 1, height: 1},
        shadowOpacity: 1,
        shadowRadius: 1,
    },
    ratingBar: {
        flex: 1, 
        marginHorizontal: 30,
        shadowOffset: {width: 1, height: 1},
        shadowOpacity: 1,
        shadowRadius: 1,
    },
    rating: {
        color: '#f1c40f',
        fontSize: 15,
        fontWeight: 'bold',
        flex: 1,
        shadowOffset: {width: 1, height: 1},
        shadowOpacity: 1,
        shadowRadius: 1,
    },
});